name: AppWright Test

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install typer requests fastapi uvicorn

      - name: Install jq for parsing JSON
        run: sudo apt-get install jq

      - name: Start backend server
        run: |
          uvicorn backend.main:app --host 127.0.0.1 --port 8000 &
          sleep 5

      - name: Submit test job and extract job_id
        id: submit
        run: |
          JOB_JSON=$(python -m cli.qgjob submit qualgent xyz123 tests/onboarding.spec.js)
          echo "🔁 Submitted: $JOB_JSON"
          echo "job_id=$(echo $JOB_JSON | jq -r '.job_id')" >> $GITHUB_ENV

      - name: Poll job status until completion
        run: |
          python -m cli.qgjob poll ${{ env.job_id }}

      - name: Fail if job failed
        run: |
          STATUS=$(python -m cli.qgjob status ${{ env.job_id }} | jq -r '.status')
          echo "Final status: $STATUS"
          if [ "$STATUS" != "completed" ]; then
            echo "❌ Test job failed"
            exit 1
          fi
